---
name: Code Scanning
on:
  pull_request:
    types:
      - closed
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm install
    - name: Install ESLint
      run: npm install eslint
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
  scan:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
  sbom:
    name: SBOM
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create package-lock.json
        run: npm install
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          trivy-config: trivy.yaml
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
