---
name: Code Scanning
on:
  pull_request:
    types:
      - closed
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Install modules
      run: npm install
    - name: Install ESLint
      run: npm install eslint
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ema-sidekick-lakewood" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: 'main'
